spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/test?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password: jaejungscene
  jpa:
    properties:
      hibernate:
        connection:
          autocommit: 'true'
        format_sql: 'true'
        show_sql: 'true'
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql
    show-sql: 'true'
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create # create, create-drop, update, validate, none
  session:
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: DEBUG
      springframework:
        web: DEBUG